#!/usr/bin/env python3
"""
Create Windows installer using NSIS.

Usage:
    python scripts/create_windows_installer.py [--cleanup]
"""
import subprocess
import sys
import shutil
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
DIST_DIR = PROJECT_ROOT / "dist"
RELEASE_DIR = PROJECT_ROOT / "release"


def find_build_dir(dist_dir: Path):
    """Find the Windows build directory or executable."""
    if not dist_dir.exists():
        return None

    # Find all directories in dist that might be the app directory
    for item in dist_dir.iterdir():
        if item.is_dir():
            # Check if it contains an exe file (likely the app directory)
            exe_files = list(item.glob("*.exe"))
            if exe_files:
                return item

    # Check if it's onefile mode (single exe file in dist)
    exe_candidates = [
        dist_dir / "anime1.exe",
        dist_dir / "Anime1.exe",
    ]

    for exe in exe_candidates:
        if exe.exists() and exe.is_file():
            # onefile mode: return parent dir as virtual app_dir
            return dist_dir

    return None


def generate_nsis_script(app_dir: Path) -> str:
    """Generate NSIS script with correct paths."""
    # Get the directory name (with correct case)
    app_dir_name = app_dir.name

    nsis_template = '''; Anime1 Desktop Windows Installer (NSIS)
; Auto-generated by create_windows_installer.py

; Compressor settings (must be at top)
SetCompressor /SOLID lzma

!define APPNAME "Anime1"
!define COMPANYNAME "Anime1"
!define DESCRIPTION "Anime1 Desktop - Anime Browser"
!define VERSIONMAJOR 0
!define VERSIONMINOR 1
!define INSTALLSIZE 120000
!define INSTDIR "$PROGRAMFILES\\${APPNAME}"

; Basic settings
Name "${APPNAME}"
Caption "${APPNAME} v${VERSIONMAJOR}.${VERSIONMINOR} - Installation Wizard"
OutFile "${SRCDIR}\\\\release\\\\anime1-windows-x64-setup.exe"
InstallDir "${INSTDIR}"
InstallDirRegKey HKLM "Software\\${COMPANYNAME}\\${APPNAME}" "InstallDir"
ShowInstDetails show
ShowUnInstDetails show

; Version info
VIProductVersion "${VERSIONMAJOR}.${VERSIONMINOR}.0.0"
VIAddVersionKey /LANG=2052 "ProductName" "${APPNAME}"
VIAddVersionKey /LANG=2052 "CompanyName" "${COMPANYNAME}"
VIAddVersionKey /LANG=2052 "FileDescription" "${DESCRIPTION}"
VIAddVersionKey /LANG=2052 "FileVersion" "${VERSIONMAJOR}.${VERSIONMINOR}.0.0"
VIAddVersionKey /LANG=2052 "LegalCopyright" "Copyright (C) 2024 ${COMPANYNAME}. All rights reserved."

; Include LogicLib for If statements
!include LogicLib.nsh

; Pre-install check
Function .onInit
    InitPluginsDir
FunctionEnd

; Installation pages
Page directory
Page instfiles

; Uninstall pages
UninstPage uninstConfirm
UninstPage instfiles

; Installation section
Section "Main Application" SecMain
    SectionIn RO

    ; Set output path
    SetOutPath "$INSTDIR"

    ; Copy entire app directory
    File /r "${SRCDIR}\\${APPDIR}"

    ; Check if app.ico exists
    IfFileExists "$INSTDIR\\app.ico" 0 SkipIcon

    ; Create shortcuts with icon
    CreateDirectory "$SMPROGRAMS\\${APPNAME}"
    CreateShortCut "$SMPROGRAMS\\${APPNAME}\\${APPNAME}.lnk" "$INSTDIR\\Anime1.exe" "" "$INSTDIR\\app.ico" 0
    CreateShortCut "$DESKTOP\\${APPNAME}.lnk" "$INSTDIR\\Anime1.exe" "" "$INSTDIR\\app.ico" 0
    Goto AfterShortcuts

SkipIcon:
    ; Create shortcuts without icon
    CreateDirectory "$SMPROGRAMS\\${APPNAME}"
    CreateShortCut "$SMPROGRAMS\\${APPNAME}\\${APPNAME}.lnk" "$INSTDIR\\Anime1.exe"
    CreateShortCut "$DESKTOP\\${APPNAME}.lnk" "$INSTDIR\\Anime1.exe"

AfterShortcuts:
    ; Create uninstaller
    WriteUninstaller "$INSTDIR\\Uninstall.exe"

    ; Add uninstall info to control panel
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "DisplayName" "${APPNAME}"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "UninstallString" '"$INSTDIR\\Uninstall.exe"'
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "InstallLocation" "$INSTDIR"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "DisplayIcon" "$INSTDIR\\app.ico"
    WriteRegStr HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "Publisher" "${COMPANYNAME}"
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "VersionMajor" ${VERSIONMAJOR}
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "VersionMinor" ${VERSIONMINOR}
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "NoModify" 1
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "NoRepair" 1
    WriteRegDWORD HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}" \\
                     "EstimatedSize" ${INSTALLSIZE}

    ; Add install info
    WriteRegStr HKLM "Software\\${COMPANYNAME}\\${APPNAME}" \\
                     "InstallDir" "$INSTDIR"
    WriteRegStr HKLM "Software\\${COMPANYNAME}\\${APPNAME}" \\
                     "Version" "${VERSIONMAJOR}.${VERSIONMINOR}"

    ; Finish
    SetAutoClose true

SectionEnd

; Uninstall section
Section "Uninstall"

    Delete "$SMPROGRAMS\\${APPNAME}\\${APPNAME}.lnk"
    RMDir "$SMPROGRAMS\\${APPNAME}"
    Delete "$DESKTOP\\${APPNAME}.lnk"

    Delete "$INSTDIR\\*.*"
    RMDir /r "$INSTDIR"

    DeleteRegKey HKLM "Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APPNAME}"
    DeleteRegKey HKLM "Software\\${COMPANYNAME}\\${APPNAME}"

    SetAutoClose true

SectionEnd
'''
    # Use forward slashes for NSIS (works on all platforms)
    src_dir = str(PROJECT_ROOT).replace('\\', '/')
    app_dir_str = app_dir_name.replace('\\', '/')

    nsis_script = nsis_template.replace('${SRCDIR}', src_dir)
    nsis_script = nsis_script.replace('${APPDIR}', app_dir_str)

    return nsis_script


def run_nsis(script_path: Path):
    """Run NSIS to create the installer."""
    # Check if NSIS is installed in common locations
    nsis_paths = [
        r"C:\Program Files (x86)\NSIS\makensis.exe",
        r"C:\Program Files\NSIS\makensis.exe",
    ]

    makensis_path = None
    for path in nsis_paths:
        if Path(path).exists():
            makensis_path = path
            print(f"[OK] NSIS found: {makensis_path}")
            break

    if not makensis_path:
        # Try using shutil.which
        import shutil
        makensis_path = shutil.which("makensis")
        if makensis_path:
            print(f"[OK] NSIS found: {makensis_path}")

    if not makensis_path:
        print("[ERROR] NSIS not found in PATH or common locations.")
        return False

    # Run NSIS
    cmd = [makensis_path, str(script_path)]
    print(f"[BUILD] Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=str(PROJECT_ROOT), capture_output=True, text=True)

    print(result.stdout)
    if result.stderr:
        print(result.stderr)

    return result.returncode == 0


def prepare_files():
    """Prepare files for installer."""
    print("[PREPARE] Preparing files for installer...")

    # Find build directory
    app_dir = find_build_dir(DIST_DIR)
    if not app_dir:
        print(f"[ERROR] Build not found in: {DIST_DIR}")
        print("[ERROR] Run 'python build.py --clean' first.")
        print(f"[INFO] Contents of {DIST_DIR}:")
        if DIST_DIR.exists():
            for item in DIST_DIR.iterdir():
                print(f"  - {item.name} ({'dir' if item.is_dir() else 'file'})")
        return None

    print(f"[OK] Found build directory: {app_dir}")

    # Ensure app.ico exists in the app directory for shortcuts
    ico_src = PROJECT_ROOT / "static" / "app.ico"
    ico_dst = app_dir / "app.ico"

    if ico_src.exists():
        shutil.copy2(ico_src, ico_dst)
        print(f"[OK] Copied app.ico to build directory: {ico_dst}")
    else:
        print(f"[WARN] app.ico not found: {ico_src}")
        print(f"[INFO] Run 'python scripts/generate_icons.py' first")

    # Ensure release directory exists
    RELEASE_DIR.mkdir(parents=True, exist_ok=True)

    print(f"[OK] Files prepared in: {DIST_DIR}")
    return app_dir


def main():
    """Main function."""
    import argparse

    parser = argparse.ArgumentParser(description="Create Windows installer")
    parser.add_argument("--cleanup", action="store_true", help="Clean up temporary files")
    args = parser.parse_args()

    print("=" * 60)
    print("Creating Windows Installer")
    print("=" * 60)

    # Prepare files
    app_dir = prepare_files()
    if not app_dir:
        sys.exit(1)

    # Generate NSIS script
    nsis_script_content = generate_nsis_script(app_dir)
    nsis_script_path = PROJECT_ROOT / "scripts" / "installer_temp.nsi"
    nsis_script_path.write_text(nsis_script_content, encoding='utf-8')
    print(f"[OK] Generated NSIS script: {nsis_script_path}")

    # Run NSIS
    if not run_nsis(nsis_script_path):
        print("[ERROR] Failed to create installer")
        # Clean up temp script
        if nsis_script_path.exists():
            nsis_script_path.unlink()
        sys.exit(1)

    # Clean up temp script
    if nsis_script_path.exists():
        nsis_script_path.unlink()
        print("[OK] Cleaned up temporary NSIS script")

    # Check output
    installer_path = RELEASE_DIR / "anime1-windows-x64-setup.exe"
    if installer_path.exists():
        size = installer_path.stat().st_size / (1024 * 1024)
        print(f"\n[OK] Installer created: {installer_path}")
        print(f"     Size: {size:.1f} MB")
    else:
        print("[WARNING] Installer not found at expected location")

    # Cleanup
    if args.cleanup:
        print("\n[CLEANUP] Cleaning up...")
        if DIST_DIR.exists():
            shutil.rmtree(DIST_DIR)
            print(f"[OK] Removed: {DIST_DIR}")


if __name__ == "__main__":
    main()
